### ISSUE TITLE
Issues with Menus on Explore

### ISSUE THREAD

**Issue by nsuberi** [resource-watch/resource-watch-app#56]
There is strange behavior of the Data menu when navigating to Explore from Homepage and clicking on dataset images.

Home (http://staging.resourcewatch.org) -> click on Data, Explore Datasets (http://staging.resourcewatch.org/explore) -> click on graphic for a dataset card, like estimated CO2 emissions

The Data menu will open and close as you repeatedly click the card's graphic. This will eventually cause the page to hang, and the tooltip over the card's graphic to remain open after the hover event ends. It will also make it so that you cannot access the Data, Insights, About, or Get Involved menus at all.

This strange lagging not happen when you approach Explore from Insights, using the "Explore Data" menu and the "All Data" option.

~~~

Another question is why the menu at the top of the page changes when you are on different pages. On Insights, the Data menu changes to a "Explore Data" menu that only has "Planet Pulse" and "All Data". This is counter-intuitive, having the menus changing depending on where in the site you are.

**Comment by mbarrenechea** [comment]
Thank you! We will check it
