### ISSUE TITLE
Legend - bug when moving items on the legend

### ISSUE THREAD

**Issue by nsuberi** [resource-watch/resource-watch-app#61]
When I use the 6-box button on the right hand side of a legend item to re-arrange the order of legend items, there is an issue if I pull a legend item down to the point where the scroll bar comes up on the right hand side of the legend box.

When I drop the legend item and try to re-arrange the legend items again, my mouse is not recognized over the 6-box button.

This doesn't happen if I re-arrange legend items without engaging the scroll bar on the legend.

**Comment by fgassert** [comment]
Thanks, I see what you mean. Let's re-check this when the explore section is more mature.
